tasks:
  - command: |
      export GP_URL=`gp url 8080 | sed 's~https://~~'`
      docker-compose up -d
      sleep 120
      ./install.sh

ports:
  - port: 8080
    onOpen: open-browser
  - port: 9200
    onOpen: ignore
  - port: 9300
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
